<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgctorSDK.Core\AgctorSDK.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Proto.Actor" Version="1.4.4" />
    <PackageReference Include="Proto.Cluster" Version="1.5.0" />
    <PackageReference Include="Proto.Remote" Version="1.5.0" />
  </ItemGroup>

</Project> 